index:
    path:     /index
    defaults: { _controller: indexBundle:Index:index }

categoria:
    path: /categoria/{nombre}
    defaults: { _controller: indexBundle:Categoria:index}

registro:
    path: /registro
    defaults: { _controller: indexBundle:Registro:registro}

login:
    path: /login
    defaults: { _controller: indexBundle:Login:login}

logout:
    path: /logout
    defaults: { _controller: indexBundle:Login:logout}