index:
    path:     /index
    defaults: { _controller: indexBundle:Index:index }

categoria:
    path: /categoria/{nombre}
    defaults: { _controller: indexBundle:Categoria:index}

registro:
    path: /registro
    defaults: { _controller: indexBundle:Registro:registro}